language: cpp

env:
  global:
    - CoverageFlags="--coverage"

os:
  - linux
# - osx

compiler:
  - gcc

script:
  - make
  - make test

after_success:
  - sudo pip install cpp-coveralls
  - coveralls -b .
